<section class="slide_cards">
<div class="conteudo-1200">
    <ul class="cards">
        <li class="card">
            <img src="<?= IMG . "/icones/selecao.png" ?>" alt="icones | <?= SEO::$Nome ?>" class="icone">
            <div class="texto">
                <p>
                    Trabalhamos com materiais de alta qualidade sempre alinhada ao tema e necessidades do cliente, prezando por segurança e o lazer.
                </p>
            </div>
        </li>
        <li class="card">
            <img src="<?= IMG . "/icones/preparacao.png" ?>" alt="icones | <?= SEO::$Nome ?>" class="icone">
            <div class="texto">
                <p>
                    Durante o evento, nossa equipe se mantém presente e acompanhando cada etapa para garantir que tudo saia conforme o planejado. Isso inclui desde a performance dos artistas até a interação com o público e o funcionamento dos equipamentos.
                </p>
            </div>
        </li>
        <li class="card">
            <img src="<?= IMG . "/icones/camadas.png" ?>" alt="icones | <?= SEO::$Nome ?>" class="icone">
            <div class="texto">
                <p>
                    Durante o evento, nossa equipe se mantém presente e acompanhando cada etapa para garantir que tudo saia conforme o planejado. Isso inclui desde a performance dos artistas até a interação com o público e o funcionamento dos equipamentos.
                </p>
            </div>
        </li>
    </ul>
</div>
</section>