<section class="footer">
    <div class="top">
        <div class="conteudo-1200">
            <div class="conteudo">
                <div class="img">
                    <img src="<?= IMG . "/icones/email.png" ?>" alt="Email | <?= SEO::$Nome ?>">
                </div>
                <div class="titulo">
                    <p>Receba novos conteudos pela nossa newsletter</p>
                </div>
                <form class="input" method="post">
                    <label for="email" class="label">
                        <img src="<?= IMG . "/icones/email-input.png" ?>" alt="Email | <?= SEO::$Nome ?>" class="icone">
                        <input id="email" name="email" type="email" class="email" placeholder="Digite seu e-mail">
                    </label>
                    <button class="send">Enviar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="copy">
        <div class="conteudo-1200">
            <div class="conteudo">
                <div class="left">
                    <div class="cp">
                        <p>@ 2024 ' <?= SEO::$Nome ?> | Todos os direitos reservados</p>
                    </div>
                </div>
                <div class="right">
                    <div class="cp">
                        Site desenvolvido por <a href="" class="Driw">
                            <p><i>Driw</i></p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>