<section class="brefing"></section>
<div class="conteudo-1200">
    <div class="brefings">
        <div class="card">
            <img src="<?= IMG . "/brefing/1.png" ?>" alt="<?= SEO::$Nome ?>" class="img">
            <div class="titulo">
                <p>SEGURANÇA</p>
            </div>
        </div>
        <div class="card">
            <img src="<?= IMG . "/brefing/2.png" ?>" alt="<?= SEO::$Nome ?>" class="img">
            <div class="titulo">
                <p>EFETIVIDADE</p>
            </div>
        </div>
        <div class="card">
            <img src="<?= IMG . "/brefing/3.png" ?>" alt="<?= SEO::$Nome ?>" class="img">
            <div class="titulo">
                <p>COMPROMETIMENTO</p>
            </div>
        </div>
    </div>
</div>
</section>