<section class="junte-se">
    <div class="conteudo-1200">
        <div class="conteudo">
            <div class="titulo">
                <p>Venha fazer parte da <br> nossa equipe</p>
            </div>
            <div class="inferior">
                <div class="left">
                    <div class="eggs">
                        <div class="egg-01"></div>
                        <div class="egg-02"></div>
                    </div>
                    <div class="info">
                        <p class="texto">Entre no link abaixo para e nós envie seu curriculo</p>
                        <a href="<?= HOME . "/formulario" ?>" class="link">
                            <p>Formulario de envio</p>
                            <div class="icone">
                                <svg width="42" height="38" viewBox="0 0 42 38" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M40.7678 20.7678C41.7441 19.7915 41.7441 18.2085 40.7678 17.2322L24.8579 1.32233C23.8816 0.346022 22.2986 0.346022 21.3223 1.32233C20.346 2.29864 20.346 3.88156 21.3223 4.85787L35.4645 19L21.3223 33.1421C20.346 34.1184 20.346 35.7014 21.3223 36.6777C22.2986 37.654 23.8816 37.654 24.8579 36.6777L40.7678 20.7678ZM-2.18557e-07 21.5L39 21.5L39 16.5L2.18557e-07 16.5L-2.18557e-07 21.5Z" fill="white" />
                                </svg>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="right">
                    <div class="info">
                        <p>Confira nossa equipe e veja quem somos nós !</p>
                        <div class="img">
                            <img src="<?= IMG . "/conteudo/home/background-confira.jpg" ?>" alt="icone arrow | <?= SEO::$Nome ?>">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>